// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7RGTXa9G2BUBgVDLQKKPRfPRNN7igsYs',
    appId: '1:749005423454:web:8b14c788cab4c5c55345cf',
    messagingSenderId: '749005423454',
    projectId: 'vstdb-c5a25',
    authDomain: 'vstdb-c5a25.firebaseapp.com',
    databaseURL: 'https://vstdb-c5a25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vstdb-c5a25.appspot.com',
    measurementId: 'G-3KX2SF5Z6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiXfkUAnqjhMUFab69oWmXWcd5_ZrJkQ',
    appId: '1:749005423454:android:a65cd0f15613b4545345cf',
    messagingSenderId: '749005423454',
    projectId: 'vstdb-c5a25',
    databaseURL: 'https://vstdb-c5a25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vstdb-c5a25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgiMF1irz8skAQnRSr1k18mIkmH9BgCPU',
    appId: '1:749005423454:ios:2f9ab275b18a9fd85345cf',
    messagingSenderId: '749005423454',
    projectId: 'vstdb-c5a25',
    databaseURL: 'https://vstdb-c5a25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vstdb-c5a25.appspot.com',
    iosClientId: '749005423454-tlaqed4uar8n4folh3b8j8q64fu7jfra.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivaskintech',
  );
  
}

